webtalk_init -webtalk_dir U:/VHDL Test/CS2022 Assignment 1/Assignment2/Assignment2.sim/arithmetic_circuit_sim/behav/xsim/xsim.dir/arithmetic_circuit_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Mar 15 14:04:20 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "18805973-9140-4c1d-b70b-7003e25d9c65" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "19def2b481244d6794ac17109aec23ed" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3392 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "7 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.06_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6224_KB" -context "xsim\\usage"
webtalk_transmit -clientid 210833581 -regid "" -xml U:/VHDL Test/CS2022 Assignment 1/Assignment2/Assignment2.sim/arithmetic_circuit_sim/behav/xsim/xsim.dir/arithmetic_circuit_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html U:/VHDL Test/CS2022 Assignment 1/Assignment2/Assignment2.sim/arithmetic_circuit_sim/behav/xsim/xsim.dir/arithmetic_circuit_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm U:/VHDL Test/CS2022 Assignment 1/Assignment2/Assignment2.sim/arithmetic_circuit_sim/behav/xsim/xsim.dir/arithmetic_circuit_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
